### ISSUE TITLE
Error when compiling with Figwheel

### ISSUE THREAD

**Issue by jkrasnay** [metosin/testit#18]
After adding testit 0.4.0 to my project, my Figwheel has started raising this error message:

[Figwheel] Compile Warning: Namespace testit.in contains a reserved JavaScript keyword, the corresponding Google Closure namespace will be munged to testit.in$  target/cljsbuild/public/js/out/testit/in.cljc   line:1  column:1

It also breaks Figwheel's reloading, which now complains: java.lang.IllegalArgumentException: Not a file: jar:file:/Users/john/.m2/repository/metosin/testit/0.4.0/testit-0.4.0.jar!/testit/in.cljc

Oddly, regular CLJS compilation works without complaint.

**Comment by jkrasnay** [comment]
I'm still having this issue. Does anyone have an opinion on this? I think maybe the testit.in ns needs to be renamed, perhaps to testit.compare or something. I'd be willing to attempt a PR if there are no objections.

**Comment by miikka** [comment]
It's unfortunate but I think the only proper way to fix this is to rename the namespace. `testit.compare` sounds like a good name to me. Please go ahead and create a PR.

**Comment by jkrasnay** [comment]
Upgrading figwheel-main from 0.1.9 to 0.2.3 appears to have fixed this issue without renaming the namespace.
